services:
  db:
    container_name: day-51
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '5003:5432'
    volumes:
      - ./db:/var/lib/postgresql/data